apiVersion: apps/v1
kind: Deployment
metadata:
  name: harmanagel-ui
  namespace: harmanagel
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: harmanagel-ui
  template:
    metadata:
      labels:
        app: harmanagel-ui
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: harmanagel-ui
          image: harmanagel/harmanagel-ui:latest
          ports:
            - containerPort: 80