apiVersion: apps/v1
kind: Deployment
metadata:
  name: harmanagel-ui
  namespace: harmanagel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: harmanagel-ui
  template:
    metadata:
      labels:
        app: harmanagel-ui
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: harmanagel-ui
          image: harmanagel/harmanagel-ui:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5