apiVersion: apps/v1
kind: Deployment
metadata:
  name: harmanagel-ui
  namespace: harmanagel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harmanagel-ui
      version: v1
  template:
    metadata:
      labels:
        app: harmanagel-ui
        version: v1
    spec:
      containers:
        - name: harmanagel-ui
          image: harmanagel/harmanagel-ui:latest
          ports:
            - containerPort: 3031
          imagePullPolicy: Always