apiVersion: v1
kind: Service
metadata:
  name: harmanagel-ui-service
  namespace: harmanagel
spec:
  selector:
    app: harmanagel-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3031
  type: ClusterIP